### ISSUE TITLE
Simon says: generate profiles as well, make them downloadable directly from the index.html

### ISSUE THREAD

**Issue by belluzj** [daltonmaag/pipeline-perf-tracker#1]
@simoncozens 

Potential tools for profiles:
* py-spy
* Linux perf tools
* scalene
* ...?

(My take: having the numbers is good already, the profiles could be made as needed by library developers for the needs of their particular work at the time)

**Comment by simoncozens** [comment]
Implemented in 3545f5c8.

I tried Scalene but some of the results were *weird* - the biggest hotspots were things like `import fs`. It just didn't make any sense.
